# Generated by Django 4.2.7 on 2023-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=30)),
                ('nachname', models.CharField(max_length=30)),
                ('profilbild', models.CharField(max_length=30)),
            ],
        ),
    ]
